### ISSUE TITLE
v1.0 Release?

### ISSUE THREAD

**Issue by notgull** [daxpedda/web-time#23]
I'm interested in using this API in `async-io`, but to do that this crate would need to have a v1.0 release.

I don't imagine that there will be any future breaking changes, as it tries to align itself with `std::time`'s API which won't have breaking changes.

**Comment by daxpedda** [comment]
Will think about it a bit, unless I come up with a reason not to, which I don't anticipate, I will get it done in the next couple of days.

**Comment by daxpedda** [comment]
Done.
https://crates.io/crates/web-time/1.0.0
