### ISSUE TITLE
Why is synchronization behind target-feature = "atomics"?

### ISSUE THREAD

**Issue by 9SMTM6** [daxpedda/web-time#33]
Hey there! 

I wonder why the synchronization with performance.timeOrigin is behind the atomics flag.

I see neither a code reason, nor a logic reason for that, at least looking only at Instant::now.

I would suggest putting it behind a cargo feature flag, if the original behavior is desirable. To keep the original api just check for either the atomics compiler flag or cargo feature flag.

**Comment by daxpedda** [comment]
`web_time::Instant` is only comparable to `web_time::Instant`, so synchronization with `performance.timeOrigin` has no value at all when its not possible to have another thread.
This way we are shaving off any unnecessary code generated in the `wasm-bindgen` JS shim.

Whats the reason for wanting to add synchronization without the atomics feature?

**Comment by 9SMTM6** [comment]
From my understanding it's very much possible to have web-workers without atomics etc, they will just serialize the data over the 'thread-boundary'.

And while in that case you won't have fast communication, having synchronized Instants might still be valuable.

**Comment by daxpedda** [comment]
> From my understanding it's very much possible to have web-workers without atomics etc, they will just serialize the data over the 'thread-boundary'.

You can, but it would be a different Rust module, in which case you are unable to compare `Instant`s between both contexts. Keep in mind that `web_time::Instant` doesn't support serialization and Serde doesn't support serialization of `std::time::Instant` either, which all makes a lot of sense to me.

**Comment by 9SMTM6** [comment]
Huh, I had not realized that these implementations were so limited. I was under the impression that the values were somehow implicitly serialized.

I have just used the 'real' wasm threads variant so far.

Thanks for clearing that up👍
